const is = {};
is.num=(arg)=>(typeof arg==='number' && !isNaN(arg));
is.nan=(arg)=>isNaN(arg);
is.str=(arg)=>typeof arg==='string';
is.bool=(arg)=>typeof arg==='boolean';
is.undef=(arg)=>typeof arg==='undefined';
is.def=(arg)=>typeof arg!=='undefined';
is.arr=(arg)=>Array.isArray(arg);
is.obj=(arg)=> arg instanceof Object;
is.fun=(arg)=>arg instanceof Function;
is.truthy=(arg)=>arg?true:false;
is.falsy=(arg)=>arg?false:true;;